---
runtime: python27 
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: hugo/public/index.html
  upload: hugo/public/index.html
  secure: always
- url: /donuts
  static_files: hugo/public/donuts/index.html
  upload: hugo/public/index.html
  secure: always
- url: /(.*)
  static_files: hugo/public/\1
  upload: hugo/public/(.*)
  secure: always
