name: Deploy to Netlify
defaults:
  run:
    working-directory:
      clojure-tech-site
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: # Manual trigger
  workflow_run:
    workflows: ["RSS Feed Sync"]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4 # Used only to install netlify cli with npm
        with:
          node-version: 18
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/663757403089/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider'
          service_account: 'blog-rss-sync@ctaymor-home.iam.gserviceaccount.com'
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Leiningen dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/project.clj') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Install Leiningen
        run: |
          curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
          chmod +x lein
          sudo mv lein /usr/local/bin/
      - name: Install Netlify CLI
        run: npm install -g netlify-cli
      - name: Download latest posts
        working-directory: clojure-tech-site
        run: lein run get-blog-cache
        continue-on-error: true
        id: download
      - name: Alert on download failure
        if: steps.download.outcome == 'failure'
        run: |
          echo "TODO: Send alert - GCS download failed"
          # Future: add actual notification here
      - name: Build site
        working-directory: clojure-tech-site
        run: lein run build43
      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=dist
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      - name: Notify on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Workflow Failed: ${context.workflow}`,
              body: `Workflow "${context.workflow}" failed in run ${context.runNumber}\n\nRun URL: ${context.payload.repository.html_url}/actions/runs/${context.runId}`
            });